@log.info("STARTED execution of 'email_trigger.rb' script")
from = @input.get("from")
to = @input.get("to")
trigger = @input.get("trigger")
cc = @input.get("cc")
subject = @input.get("subject")
date = @input.get("date")
body = @input.get("body")
content_type = @input.get("content-type")
 
@log.info("Triggered script : #{trigger}")
@log.info("Got mail From : #{from}")
@log.info("To : #{to}")
@log.info("Cc : #{cc}")
@log.info("Subject : #{subject}")
@log.info("Date : #{date}")
@log.info("Body : #{body}")
@log.info("Content-type :#{content_type}")
 
@log.info("FINISHED execution of 'email_trigger.rb' script")
